### ISSUE TITLE
Send survey to estimate number of attendants

### ISSUE THREAD

**Issue by smoia** [ohbm/hackathon2022#1]
- [x] BHG Mattermost
- [ ] OHBM member
- [x] Neurostars
- [x] FSL 
- [x] SPM
- [ ] Freesurfer
- [x] MRtrix

**Comment by htwangtw** [comment]
I am a bit surprised that we didn't thought about sending through OHBM. This might be something we can request. 
After thinking about potential overlaps and OHBM membership I think we can target:
- OHBM member
- Brainhack mattermost
- Neurostars
- Brainstorm
- FSL 
- SPM
- Freesurfer

WDYT @smoia

**Comment by smoia** [comment]
Yeah that makes sense! Agreed and updated!

**Comment by katjaq** [comment]
heyy! Lovely collection of contact lists. I don't want to discourage you -- just maybe encourage you to contact ohbm early on. We were not able to send through ohbm list as they request (for me "a ton" of) money for you to make use of the list ........ But please try again and contact ohbm and maybe they will at some point change their mind :)
Good luck!

**Comment by emdupre** [comment]
I'm not aware that an email blast for a SIG event would require payment, but please let me know if so !
Unrelatedly, I just wanted to ping in that you could consider (co-)writing a blogpost to advertise upcoming OSSIG events and embed a survey in the post. That's definitely something we (the OHBM twitter account) can promote, too.
