### ISSUE TITLE
Add Discord info/how to

### ISSUE THREAD

**Issue by anibalsolon** [ohbm/hackathon2022#14]
Good example content

https://docs.google.com/document/d/1d8WByqS62LeoHgqY65Zy1TVbO4HG9BRdDgWg81jeaQY/edit

- [x] [Welcome screen](https://support.discord.com/hc/en-us/articles/360043913591)
- [x] Quick getting-started guide
- [x] Rules
- [x] Channel descriptions
- [ ] FAQ, resources

**Comment by r03ert0** [comment]
Hi @anibalsolon!
Why not using brainhack mattermost? That would allow new people to integrate a discussion channel that has already >5000 users. Many people from the brainhack community already have an account, and many channels are very active on a year round basis.
The brainhack instance is self-hosted, and currently it's @ntraut from our lab who's maintaining it.
(...if there's a plan to start migrating the whole community to discord, please let us know 🙏 )

**Comment by anibalsolon** [comment]
Hi @r03ert0, we chose to go with Discord as it provides text/audio/video in one place, and other features such as roles and integrations we are developing.

We do not intend to migrate the community, it is mainly for the hackathon! Projects have the option to use the communication channel that they prefer.

**Comment by r03ert0** [comment]
we added an add on for having video chats some time ago :)
it's the small "camera" icon on the top right:

<img width="173" alt="Screenshot 2022-04-20 at 19 32 18" src="https://user-images.githubusercontent.com/2310732/164289204-405cb18d-401f-4157-a307-00cc84eb24ce.png">

there's also a quite powerful collaborative "playbooks" functionality (matrix icon on the top left):
<img width="194" alt="Screenshot 2022-04-20 at 19 33 46" src="https://user-images.githubusercontent.com/2310732/164289422-3afe9071-2542-4fbf-974c-c57e13ef836a.png">

I'm all for allowing people to use whatever platform they want. The datalad crowd, for example, have been using Matrix. We recently added a bot that lets them connect their Matrix datalad channel with mattermost.brainhack datalad channel.

Maybe you would consider adding a Mattermost.Brainhack button close to the Discord button in the webpage?

**Comment by anibalsolon** [comment]
Yes, we will promote for people to join the Mattermost as well!

**Comment by AKSoo** [comment]
> we added an add on for having video chats some time ago :) it's the small "camera" icon on the top right:

I also would have preferred sticking to existing platforms, but apparently scaling Jitsi (which the chat add-on uses) can be tricky.

> I'm all for allowing people to use whatever platform they want. The datalad crowd, for example, have been using Matrix. We recently added a bot that lets them connect their Matrix datalad channel with mattermost.brainhack datalad channel.

Unfortunately, connecting the entire Hackathon server with Mattermost will not be feasible because the Discord server has multiple channels. We will look into relaying announcements to the Mattermost hackathon channel though!

**Comment by r03ert0** [comment]
thank you @AKSoo

We use the jitsi chat all the time and we have had no problems with scalability. We've even used it for presentations (Zoom or Crowdcast may be better alternatives for having >50 people), but for the typical number of participants in a hackathon project (<10?) there should be no concern.

Channeling the whole hackathon discord to a single mattermost.brainhack channel would provide indeed a very poor experience. However, we do not limit the creation of new channels. We've used mattermost.brainhack for several hackathons in the past, and individual hackathon projects have created their own channel. I don't see why this became a problem now, and we haven't had complaints from the users. On the contrary, many of these hackathon channels are still active and have transformed into permanent discussion channels for projects that lead to collaboration and publications. Even rather large projects like PrimeDE or BigBrain use mattermost.brainhack...

**Comment by AKSoo** [comment]
> However, we do not limit the creation of new channels.

It does appear [Mattermost](https://api.mattermost.com/#operation/CreateChannel) has API. With some work, it should be possible to set up a bot that automatically creates Mattermost channels matching Discord channels and sets up [bridges](https://github.com/42wim/matterbridge) between each pair, but...

> We use the jitsi chat all the time and we have had no problems with scalability. We've even used it for presentations (Zoom or Crowdcast may be better alternatives for having >50 people), but for the typical number of participants in a hackathon project (<10?) there should be no concern.

If so, I am also not sure benefits of Discord (text/video chat in one place, roles) is worth adding another platform for users and staff to manage. I suppose if the integration is smooth, users can choose to be wherever they prefer...

**Comment by anibalsolon** [comment]
Projects can indeed choose the platform they'd like to use, yes, we would never limit that. The goal here is to provide an easy hybrid space, in which people can be immersed in the event, participate in the synchronous events, and seamlessly jump between projects. In Discord, with video channels, people can do so. We also have control over the main stage, for e.g. who can speak and call people on stage.

Projects that already have channels in Mattermost can still use it to communicate during the event if they like to. It is not a problem at all @r03ert0 .
